name: publish alpine
on: workflow_dispatch
  
jobs:
  publish:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write
      
    steps:
      - run: |
          set -xe
          docker pull alpine:latest
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u moda --password-stdin
          docker tag $(docker images alpine:latest -q) ghcr.io/timburgan-org1/alpine:latest
          docker push ghcr.io/timburgan-org1/alpine:latest
      
